camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    webapp:
      auth:
        cache:
          ttl-enabled: false
    authorization:
      enabled: false
      enabled-for-custom-code: false
      authorization-check-revokes: false
      tenant-check-enabled: false
    default-number-of-retries: 1


logging:
  appender:
    name: STDOUT
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%mdc] %-5level %logger{40} - %msg%n'
  level:
    root: info
  charset:
    console: UTF-8
